---
title: "Research"
toc: false
page-layout: article
css: styles.css
---
## Forthcoming

<div class="paper-entry">
<p class="paper-title"><a href="research/paper1.html">Machine Learning for Detecting Collusion and Capacity Withholding  in Wholesale Electricity Marketst</a></p>
<p class="paper-meta">Forthcoming</p>
<p class="paper-abstract">Collusion and capacity withholding in electricity wholesale markets are important mechanisms of market manipulation. This study applies a refined machine learning–based cartel-detection algorithm to two cartel cases in the Italian electricity market and evaluates its out-of-sample performance. Specifically, we consider an ensemble machine learning method that uses statistical screens constructed from offer-price distributions in balancing markets as predictors for the incidence of collusion among electricity providers in specific regions. We also propose novel screens capturing the capacity-withholding behavior of electricity providers and find that including such screens-derived from the day-ahead spot market rather than the balancing market-can improve cartel detection. When the screens are computed from all offers submitted in a market session, both the classic, balancing-market screens and the novel day-ahead screens correctly classify almost all sessions in our data as collusive or competitive, with the combination of both achieving the highest average performance. When the classic screens are computed separately for subsets of participants within a session - an approach tailored to detecting incomplete cartels as some of the bidders in collusive sessions may not participate in the cartel - the performance of our machine learning approach remains similarly high, with correct-classification rates close to 100\%. Overall, the study provides a proof of concept for the strong potential of supervised machine learning techniques to detect and dismantle cartels in electricity markets.</p>
<p class="paper-links">
<a href="files/paper_energy_compressed.pdf"><i class="bi bi-file-earmark-pdf"></i> Forthcoming publication</a>
<a href="#"><i class="bi bi-easel2"></i> Slides</a>
<a href="https://github.com/iamarin"><i class="bi bi-github"></i> Code</a>
</p>
</div>


## Work in Progress

<div class="paper-entry">
<p class="paper-title"><a href="research/paper1.html">Antitrust Market Integration Determinants: Geographic Antitrust Markets for Public Procurement</a></p>
<p class="paper-meta">Working Paper</p>
<p class="paper-abstract">Many methods have been proposed for geographical market delineation, yet most are considered as data-intensive and technically demanding. This study operationalizes market delineation not only through price-based substitutability, but also by modeling the emergent geography of supplier relationships. We use an Exponential Random Graph model to test whether agglomeration effects, proximity mechanisms, and structural network features jointly determine where market boundaries are drawn in practice. We identify local markets based on bidding behavior in paving tenders from Quebec's construction sector between 2012 and 2019.</p>
<p class="paper-links">
<a href="#"><i class="bi bi-file-earmark-pdf"></i> Working Paper</a>
<a href="#"><i class="bi bi-easel2"></i> Slides</a>
<a href="https://github.com/iamarin"><i class="bi bi-github"></i> Code</a>
</p>
</div>

<div class="paper-entry">
<p class="paper-title"><a href="research/paper1.html">Bussiness as usual: The case of the antitrust inquiry in Quebec, Canada</a></p>
<p class="paper-meta">Job Market Paper</p>
<p class="paper-abstract">This paper analyzes the dynamic impact of antitrust intervention on competition outcomes in public procurement markets. Leveraging the largest antitrust inquiry in Quebec between 2011 and 2014, I implement a panel event-study analysis and a difference-in-differences approach to identify the effects of antitrust enforcement on different levels of procurement outcomes. I rely on an entropy covariate strategy to improve the balance between treated and untreated municipalities, and combine matching and panel fixed-effects methods to uncover the effects of policy intervention. I estimate the average treatment effect and then disaggregate the effect over time after the intervention to understand the dynamic effects of the intervention. I also investigate the heterogeneity of treatment effects for relevant players in the market notably the case of cartel related and regional level firms. While I am unable to identify lasting effects on the procurement market for the bid-rigging case at hand, I show that antitrust intervention significantly alters the strategy of key players in the market.</p>
<p class="paper-links">
<a href="#"><i class="bi bi-file-earmark-pdf"></i> Working Paper</a>
<a href="files/paper2_slides_jdd.pdf"><i class="bi bi-easel2"></i> Slides</a>
<a href="https://github.com/iamarin"><i class="bi bi-github"></i> Code</a>
</p>
</div>

